background {
    monitor =
    color = rgba(111111ee)
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2

    outer_color = rgb(151515)
    inner_color = rgb(101010)
    font_color = rgb(ffffff)

    rounding = 10

    position = 0, -20
    halign = center
    valign = center
}
