# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"  # You can switch to "powerlevel10k/powerlevel10k" if you install it

# Plugins
plugins=(
  git
  z
  sudo
  history-substring-search
  zsh-autosuggestions
  zsh-syntax-highlighting
)

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Preferred PATH (put custom bins before system ones)
export PATH="$HOME/.local/share/nvim/lsp_servers/lua_ls/bin:$HOME/.local/bin:$HOME/bin:/usr/local/bin:$PATH"

# History search with up/down arrows
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Useful aliases
alias ..='cd ..'
alias ...='cd ../..'
alias c='clear'

# Tmux session named after current directory
alias tmuxdir='tmux new -s "$(basename "$PWD")"'

# new better tmux fzf everythig mixed
bindkey -s '^f' 'tmux-sessionizer.sh\n'

# Safer file operations
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# Git shortcuts
alias gst='git status'
alias gl='git pull'
alias gp='git push'
alias ga='git add'
alias gc='git commit -m'

# Edit and reload .zshrc
alias zrc='nvim ~/.zshrc && source ~/.zshrc'

# Language / Locale (optional but good to set)
export LANG=en_US.UTF-8

# Uncomment if using terminal with Nerd Font
# export POWERLEVEL9K_MODE='nerdfont-complete'

# Optional: Editor setting
export EDITOR='nvim'

# Enable command auto-correction
ENABLE_CORRECTION="true"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"

nvm() {
  unset -f nvm
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  nvm "$@"
}

#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
export PATH=$JAVA_HOME/bin:$PATH

# Use ripgrep for fzf (super fast search)
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
# CTRL+R with preview (history search)
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:wrap"

# Better ls
alias ls='eza --icons'
alias ll='eza -lh --icons'
alias la='eza -lah --icons'

# Better cat
alias cat='bat'

# Better disk usage
alias du='du -h'
alias df='df -h'

# Safer delete
alias trash='trash-put'
